server:
  port: 8085

logging:
  level:
    com:
      alphbank:
        signingservice: DEBUG
    org:
      springframework:
        web: INFO
    reactor:
      netty:
        http:
          client:
            HttpClient: INFO
          server:
            HttpServer: INFO

alph:
  signingservice:
    # This application is not hosted, so I cannot create a proper link for the frontend. Currently it's a relative link
    signingServiceUrlTemplate: /signing/%s

alph-commons:
  wiretapEnabled: false

spring:
  main:
    web-application-type: reactive
  application:
    name: SigningService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/signing
    username: alph
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5432/signing
    user: alph
    password: admin
    validate-on-migrate: true
    locations: classpath:/db/migration
  rabbitmq:
    host: localhost
    username: alph
    password: admin
    routing-key: signingservice.status.update
    exchange: signingservice