version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5438:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: customer

  adminer:
    image: adminer
    restart: always
    ports:
      - 5439:8080