server:
  port: 8083

logging:
  level:
    com:
      alphbank:
        corecustomerservice: DEBUG
    org:
      springframework:
        web: DEBUG

spring:
  main:
    web-application-type: reactive
  application:
    name: CoreCustomerService
  r2dbc:
    driverClassName: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5438/Alex
    username: Alex
    password: admin
  jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/Alex
    username: Alex
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5438/Alex
    user: Alex
    password: admin
    enabled: true
    validate-on-migrate: true
    locations: classpath:/db/migration