server:
  port: 8083

logging:
  level:
    com:
      alphbank:
        corecustomerservice: DEBUG
    org:
      springframework:
        web: DEBUG

spring:
  main:
    web-application-type: reactive
  application:
    name: CoreCustomerService
  r2dbc:
    url: r2dbc:postgresql://localhost:5438/customer
    username: customer
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5438/customer
    user: customer
    password: admin
    validate-on-migrate: true
    locations: classpath:/db/migration