server:
  port: 8081

logging:
  level:
    com:
      alphbank:
        corepaymentservice: DEBUG
    org:
      springframework:
        web: DEBUG

client:
  coreaccountservice:
    internal:
      uri: http://localhost:8080/internal_account

spring:
  main:
    web-application-type: reactive
  application:
    name: CorePaymentService
  r2dbc:
    driverClassName: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5434/Alex
    username: Alex
    password: admin
  jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/Alex
    username: Alex
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5434/Alex
    user: Alex
    password: admin
    enabled: true
    validate-on-migrate: true
    locations: classpath:/db/migration