logging:
  level:
    com:
      alphbank:
        corepaymentservice: DEBUG
    reactor:
      netty:
        http:
          client:
            HttpClient: INFO
          server:
            HttpServer: INFO

alph-commons:
  wiretapEnabled: false

server:
  port: 8081

alph:
  client:
    coreaccountservice:
      internal:
        uri: http://localhost:8080/internal_account

spring:
  main:
    web-application-type: reactive
  application:
    name: CorePaymentService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment
    username: alph
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5432/payment
    user: alph
    password: admin
    validate-on-migrate: true
    locations: classpath:/db/migration