version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: Alex

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080