logging:
  level:
    com:
      alphbank:
        coreaccountservice: DEBUG

spring:
  main:
    web-application-type: reactive
  application:
    name: CoreAccountService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/account
    username: alph
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5432/account
    user: alph
    password: admin
    validate-on-migrate: true
    locations: classpath:/db/migration