server:
  port: 8082

logging:
  level:
    com:
      alphbank:
        coreloanservice: DEBUG
    org:
      springframework:
        web: DEBUG

client:
  coreaccountservice:
    internal:
      uri: http://localhost:8080/api/internal_account

spring:
  main:
    web-application-type: reactive
  application:
    name: CoreLoanService
  r2dbc:
    driverClassName: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5436/Alex
    username: Alex
    password: admin
  jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/Alex
    username: Alex
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5436/Alex
    user: Alex
    password: admin
    enabled: true
    validate-on-migrate: true
    locations: classpath:/db/migration
  rabbitmq:
    host: http://localhost:5672
    username: Alex
    password: admin
    routing-key: loan.event.payout
    exchange: loan