server:
  port: 8082

logging:
  level:
    com:
      alphbank:
        coreloanservice: DEBUG
    org:
      springframework:
        web: DEBUG
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG
          server:
            HttpServer: DEBUG

alph:
  client:
    coreaccountservice:
      internal:
        uri: http://localhost:8080/api/internal_account

alph-commons:
  wiretapEnabled: true

spring:
  main:
    web-application-type: reactive
  application:
    name: CoreLoanService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loan
    username: alph
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5432/loan
    user: alph
    password: admin
    validate-on-migrate: true
    locations: classpath:/db/migration
  rabbitmq:
    host: http://localhost:5672
    username: Alex
    password: admin
    routing-key: loan.event.payout
    exchange: loan