@startuml


queue "RabbitMQ" as rabbitsign

[payment-service] as payment
[signing-service] as signing
[government-request-service] as govreq
[fraud-analysis-service] as fraud
[know-your-customer-service] as kyc


[core-account-service] as caccount
[core-customer-service] as ccustomer
[core-payment-service] as cpayment


actor "Svelte Frontend" as svelte
actor Government

Government --> govreq

svelte --> payment
svelte --> signing
svelte --> kyc

payment --> signing
signing --> rabbitsign 
rabbitsign --> payment
payment --> cpayment
payment --> fraud

govreq --> caccount
govreq --> cpayment
govreq  --> ccustomer

svelte --> caccount
svelte --> cpayment
svelte --> ccustomer

@enduml