@startuml

queue "RabbitMQ" as rabbitloan 
queue "RabbitMQ" as rabbitsign


[signing-service] as signing

[credit-worthiness-assessment-service] as creditworth
[loan-application-service] as loan
[know-your-customer-service] as kyc


[government-reporting-transfer-service] as govtransfer
[government-request-service] as govreq



[core-account-service] as caccount
[core-customer-service] as ccustomer
[core-payment-service] as cpayment
[core-loan-service] as cloan


actor "Svelte Frontend" as svelte
actor Government

Government --> govreq
govtransfer --> Government

svelte --> signing
svelte --> kyc
svelte --> loan

cloan --> rabbitloan 
rabbitloan --> govtransfer
signing --> rabbitsign
rabbitsign--> loan

loan --> creditworth
loan --> cloan
loan --> signing

govreq --> caccount
govreq --> cpayment
govreq --> cloan
govreq  --> ccustomer

svelte --> caccount
svelte --> cpayment
svelte --> cloan
svelte --> ccustomer

@enduml