server:
  port: 8086

logging:
  level:
    com:
      alphbank:
        loanapplicationservice: DEBUG
    org:
      springframework:
        web: INFO
    reactor:
      netty:
        http:
          client:
            HttpClient: INFO
          server:
            HttpServer: INFO

alph:
  client:
    core-loan-service:
        uri: http://localhost:8082
    signing-service:
      uri: http://localhost:8085
      document-to-sign-template: "I hereby authorize this loan application of %s %s with a yearly fixed interest rate of %s%% and %s monthly installments, totalling %s %s, resulting in a cost of %s %s."

alph-commons:
  wiretapEnabled: false

spring:
  main:
    web-application-type: reactive
  application:
    name: LoanApplicationService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loanapplication
    username: alph
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5432/loanapplication
    user: alph
    password: admin
    validate-on-migrate: true
    locations: classpath:/db/migration
  rabbitmq:
    host: localhost
    username: alph
    password: admin
    loan-application-signing-status-routing-key: signingservice.status.update
    loan-application-signing-status-exchange: signingservice
    loan-application-signing-status-queue: loanapplication.signing